packages:
  - "apps/*"
  - "packages/*"
nodeLinker: hoisted
allowBuilds:
  browser-tabs-lock: false
  core-js: false
  esbuild: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.7'
  - '@turbo/darwin-arm64@2.11.7'
  - '@turbo/linux-64@2.11.7'
  - '@turbo/linux-arm64@2.11.7'
  - '@turbo/windows-64@2.11.7'
  - '@turbo/windows-arm64@2.11.7'
  - turbo@2.11.7
  - convex-helpers@0.1.125
